config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  get '/events/search', to: 'events#search'

  resources :group_messages, only: [:create]
  resources :direct_messages, only: [:create]
  #resources :event_users
  resources :events
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/users/:first_id/direct_message/:second_id', to: 'direct_messages#display_messages', as: 'display_direct_messages'
  get '/users/:user_id/group_message/:event_id', to: 'group_messages#display_messages', as: 'display_group_messages'

  get "/events/:event_id/register", to: "events#register", as: 'event_register_user'
  get "/events/:event_id/unregister", to: "events#unregister", as: 'event_unregister_user'
  #get "/events/:user_id/organizer", to: "events#organizer", as: 'organizer'
  post "/events/:event_id/organizer/add_member", to: "events#add_member", as: 'add_member'
  get "/events/:event_id/organizer/:member_id/remove_member", to: "events#remove_member", as: 'remove_member'


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' #make it post or delete

  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
    belongs_to :sender, class_name: 'User'
	belongs_to :receiver, class_name: 'User'
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController

    def display_messages 
        @receiver = User.find(params[:second_id])
        @messages = DirectMessage.where(sender_id: session[:user_id], receiver_id: @receiver.id).or(DirectMessage.where(sender_id: @receiver.id, receiver_id: session[:user_id]))
        @direct_id = [@receiver.id, session[:user_id]].sort().join("")

    end 

    def create 
        @message = DirectMessage.create(sender_id: session[:user_id], receiver_id: params[:receiver_id], message: params[:message])
       SendDirectMessageJob.perform_later(@message)
       #redirect_to request.referrer 
    end 
end

app/helpers/direct_messages_helper.rb
module DirectMessagesHelper
end

app/views/direct_messages/_message.html.erb
<div  style="<%= message.receiver.id == current_user.id ?  "background-color: lightblue;" : "border-color: #dedede; background-color: #f1f1f1;" %>">
    <p class= "pl-2" style="word-wrap:break-word;"><span style="font-weight: bold;"><%= message.sender.first_name%></span> : <%= message.message %></p>
<p class= "pl-2" style="font-size:12px;"><%= (message.created_at - 4.hours).strftime("%b %d, %Y  at %I:%M %p") %></p>
    <hr>
</div>

app/views/direct_messages/_receiver.html.erb
<div  style="background-color: lightblue;" %> <!-- #ccc;-->
    <p class= "pl-2" style="word-wrap:break-word;"><span style="font-weight: bold;"><%= message.sender.first_name%></span> : <%= message.message %></p>
    <p class= "pl-2" style="font-size:12px;"><%= (message.created_at - 4.hours).strftime("%b %d, %Y  at %I:%M %p") %></p>
    <hr>
</div>

app/views/direct_messages/_sender.html.erb
<div  style="background-color: #f1f1f1;" >
    <p class= "pl-2" style="word-wrap:break-word;"><span style="font-weight: bold;"><%= message.sender.first_name%></span> : <%= message.message %></p>
<p class= "pl-2" style="font-size:12px;"><%= (message.created_at - 4.hours).strftime("%b %d, %Y  at %I:%M %p") %></p>
    <hr>
</div>

app/views/direct_messages/display_messages.html.erb
<div class="container mt-3">
    <input type="hidden" id="receiver_id", value="<%= @receiver.id %>">
    <h1 class="text-center">Direct Chat: <%= @receiver.first_name %> </h1>
    <br>

    <div class="row d-flex justify-content-center">
        <div class="column col-md-9">
            <div class="message" id="message-scroll-bottom">
                <% if @messages %>
                    <div id="messages" class="ml-2 ">
                        <% @messages.each do |message| %>
                            <%= render "direct_messages/message", message: message %>
                        <% end %>
                    </div>
                <% end %>

                <div class="ml-2 " >

                    <%= form_tag direct_messages_path  do %>
                        <div class="form-group d-flex mr-2 ">

                            <%= text_field_tag :message, nil,  placeholder: 'Type message here...', class: 'form-control' %>
                            <%= hidden_field_tag "receiver_id", params[:second_id] %>
                            <%= hidden_field_tag "direct_id", @direct_id %>
                            <%= submit_tag "Send", class: "btn btn-primary ml-2", data: { disable_with: false } %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<%= javascript_pack_tag 'message_scroll' %>