config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  get '/events/search', to: 'events#search'

  resources :group_messages, only: [:create]
  resources :direct_messages, only: [:create]
  #resources :event_users
  resources :events
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/users/:first_id/direct_message/:second_id', to: 'direct_messages#display_messages', as: 'display_direct_messages'
  get '/users/:user_id/group_message/:event_id', to: 'group_messages#display_messages', as: 'display_group_messages'

  get "/events/:event_id/register", to: "events#register", as: 'event_register_user'
  get "/events/:event_id/unregister", to: "events#unregister", as: 'event_unregister_user'
  #get "/events/:user_id/organizer", to: "events#organizer", as: 'organizer'
  post "/events/:event_id/organizer/add_member", to: "events#add_member", as: 'add_member'
  get "/events/:event_id/organizer/:member_id/remove_member", to: "events#remove_member", as: 'remove_member'


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' #make it post or delete

  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/group_message.rb
class GroupMessage < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/controllers/group_messages_controller.rb
class GroupMessagesController < ApplicationController

    def display_messages 
        @user = current_user  #gets the current logged-in user 
        @event = Event.find(params[:event_id])
        @joined = @event.is_user_joined(@user) 
        @organizer = @event.is_user_organizer(@user)
        if @joined            #verify if user is allowed to see the event's chat
            @messages = GroupMessage.where(event_id: params[:event_id])
            @members = @event.users 
        else 
            redirect_back(fallback_location: user_path(@user))
        end 
    end 

    def create
        @message = GroupMessage.create(user_id: session[:user_id], event_id: params[:event_id], message: params[:message])
        #redirect_to request.referrer 
        # ActionCable.server.broadcast "group_channel_#{@message.event_id}", message: @message.message 
        SendMessageJob.perform_later(@message)
    end 
end

app/helpers/group_messages_helper.rb
module GroupMessagesHelper
end

app/views/group_messages/_message.html.erb
<div>
    <p><span style="font-weight: bold;"><%= message.user.first_name%></span> : <%= message.message %></p>
    <p style="font-size:12px;"><%= (message.created_at - 4.hours).strftime("%b %d, %Y  at %I:%M %p") %></p>
<hr>
</div>

app/views/group_messages/display_messages.html.erb
<div class="container mt-3">
<h1 class="text-center">Group Chat: <%= @event.title %> </h1>
<br>
<br>

<div class="row d-flex justify-content-between">
    <div class="column col-md-8">
        <!-- display messages -->
        <div class="group-message message" id="message-scroll-bottom">
            <div class="added">
                <% if @messages %>
                <div id="messages", class="ml-2 mt-2 ", event_id="<%= @event.id %>">
                        <% @messages.each do |message| %>
                            <%= render "group_messages/message", message: message %>
                        <% end %>
                </div>
                <% end %>
                <!-- display message input box -->
                <div class="ml-2" >
                <%= form_tag group_messages_path  do %>
                    <div class="form-group d-flex mr-2 ">
                        <%= text_field_tag :message, nil,  placeholder: 'Type message here...', class: 'form-control'%>
                        <%= hidden_field_tag "event_id", params[:event_id] %>
                        <%= submit_tag "Send", class: "btn btn-primary ml-2", data: { disable_with: false }%>
                    </div>
                <% end %>
                </div>
            </div> <!-- added -->
        </div>
    </div>


    <div class="card column col-md-4 event-members">
        <div class="card-header">
            Members : <%= @members.length %>
        </div>
        <ul class="list-group list-group-flush">
            <% @members.each do |member| %>
                <li class="list-group-item d-flex justify-content-between"><a href="/users/<%=@user.id%>/direct_message/<%=member.id %>"><%= member.first_name%> <%=member.last_name %> </a>
                <% if @organizer && member != @user %>
                     <span class="ml-3"><%= button_to "Remove", "/events/#{@event.id}/organizer/#{member.id}/remove_member", :method => "get", class: "btn btn-outline-danger"%></span>
                <% end %>
                </li>

            <% end %>
        </ul>

<!-- -->
        <% if @organizer %>
            <%= form_for( :events, as: :email, url: "/events/#{@event.id}/organizer/add_member", method: :post, html: { class: "d-inline-flex p-2 bd-highlight"})  do |f| %>
                    <div class="form-group d-flex justify-content-center">
                        <%= f.text_field :email, placeholder: "User Email", class: "form-control" %>
                        <%= f.submit "Add", :class => "btn btn-primary ml-2", data: { disable_with: false }%>
                    </div>
                <% end %>
                <% if flash[:error] %>
                    <p style="color: red" class="text-center"><%= flash[:error] %></p>
                <% end %>
            <% end %>
    </div>
    </div>
</div>

<%= javascript_pack_tag 'message_scroll' %>