config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  get '/events/search', to: 'events#search'

  resources :group_messages, only: [:create]
  resources :direct_messages, only: [:create]
  #resources :event_users
  resources :events
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/users/:first_id/direct_message/:second_id', to: 'direct_messages#display_messages', as: 'display_direct_messages'
  get '/users/:user_id/group_message/:event_id', to: 'group_messages#display_messages', as: 'display_group_messages'

  get "/events/:event_id/register", to: "events#register", as: 'event_register_user'
  get "/events/:event_id/unregister", to: "events#unregister", as: 'event_unregister_user'
  #get "/events/:user_id/organizer", to: "events#organizer", as: 'organizer'
  post "/events/:event_id/organizer/add_member", to: "events#add_member", as: 'add_member'
  get "/events/:event_id/organizer/:member_id/remove_member", to: "events#remove_member", as: 'remove_member'


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' #make it post or delete

  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/user.rb
class User < ApplicationRecord
    has_many :event_user #plural gave an error 
    has_many :group_messages
    has_many :events, through: :event_user
    

    has_many :direct_messagee, foreign_key: :receiver_id, class_name: 'DirectMessage'  
	has_many :senders, through: :direct_messagee
	has_many :direct_messaged, foreign_key: :sender_id, class_name: 'DirectMessage' #user can message many users.  The messaged users are accessed by the reciever_id
    has_many :receivers, through: :direct_messaged
    
    has_secure_password 
    validates :email, presence: true, uniqueness: true


    #this may better be in DirectMessage 
    def people_messaged
        #DirectMessage.where(sender_id: self.id).or(DirectMessage.where(reciever_id: self.id)).distinct
        #DirectMessage.where(reciever_id: self.id).distinct
        DirectMessage.all.select {|m| m.receiver_id == self.id}.uniq {|i| i.sender_id} #retuns a list of direct messages, unique by sender_id 
    end 


        #return all events of an organizer 
    # def organized_events 
    #     event_users = EventUser.where(user_id: self.id, organizer: true)
    #     event_users.map do |event_user|
    #         event_user.event
    #     end 
    # end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate, :except => [:new, :create]

    def show 
        #only logged in user have access to this route 
        @user = current_user 
        @popular_events = Event.popular 
    end 

    def new 
        @user = User.new 
    end 

    def create 
        @user = User.create(user_params)
        if @user.valid?  
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else 
            redirect_to new_user_path 
            flash[:errors] = @user.errors.full_messages 
        end 
    end 


    private 
    def user_params 
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="container mt-3">
    <h1 class="text-center">Sign Up</h1>

    <% if flash[:errors] %>
        <div class="form-group row justify-content-center mt-2">
            <div class="col-lg-4">
                <% flash[:errors].each do |error| %>
                    <p style="color:red"> <%= error%> </p>
                <% end %>
            </div>
        </div>
    <% end %>

    <%= form_for @user do |f| %>
        <div class="form-group row justify-content-center">
            <div class="col-lg-4">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: "form-control" %>
            </div>
        </div>
    
        <div class="form-group row justify-content-center">
            <div class="col-lg-4">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: "form-control" %>
            </div>
        </div>


        <div class="form-group row justify-content-center">
            <div class="col-lg-4">

                <%= f.label :email %>
                <%= f.text_field :email, class: "form-control" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <div class="col-lg-4">
                <%= f.label :password %>
                <%= f.text_field :password, class: "form-control" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <div class="col-lg-4">
                <%= f.label :password_confirmation %>
                <%= f.text_field :password_confirmation, class: "form-control" %>
            </div>        
        </div>

        <div class="row justify-content-center">
            <%= f.submit "Sign up", :class => "btn btn-primary" %>
        </div>
    <% end %>
        
    <br>
    <div class="row justify-content-center">
        <%= link_to "Already have an account? Log in here", "/login" %>
        </div>
</div>

app/views/users/show.html.erb
<div class="container">
<h1 class="mt-4 text-center">Welcome <%= @user.first_name %> </h1>

<br>
<div class="d-flex justify-content-between">
<div id="events">
    <div class="card" style="width: 20rem;">
    <div class="card-header text-white bg-dark">
        <h3>Your Events</h3>
    </div>
    
        <% if @user.events.length > 0 %> 
        <ul class="list-group list-group-flush">
            <% @user.events.each do |event|%>
            <li class="list-group-item"><%=link_to event.title, event_path(event) %></li>
            <% end %>
        </ul>
        <% else  %> 
        <div class="card-body">
            <p class="card-text">You have no events!! </p>
            <p class="card-text"><%=link_to "Search Events", events_path %></p>
        </div>
        <% end %> 
   
    </div>
    <div class="text-center">
         <%=button_to "Create Event", new_event_path,class:"btn btn-dark mt-3", :method => "get"%>
    </div>
    
</div>
<br>
<br>

<div id="messages"> 
    
    

    <div class="card" style="width: 18rem;">
    <div class="card-header text-white bg-dark">
        <h3>Messages:</h3>
    </div>
    <div class="card-header">
        <h5>Group Messages:</h5>
    </div>
        
        <% if @user.events.length > 0 %>
        <ul class="list-group list-group-flush">
            <% @user.events.each do |event| %> 
            <li class="list-group-item"><%= link_to event.title, "#{@user.id}/group_message/#{event.id}" %></li>
            <% end %>
        </ul>
        <% else %>
            <div class="card-body">
            <p class="card-text">Add events to see messages! </p>
            <p class="card-text"><%=link_to "Search Events", events_path %></p>
        </div>
        <% end %>
      
    </div>


    <br>


    <div class="card" style="width: 18rem;">
    <div class="card-header">
        <h5>Direct Messages:</h5>
    </div>
    <% if @user.people_messaged.length >0 %>
    <ul class="list-group list-group-flush">
            <% @user.people_messaged.each do |msg| %> 
            <li class="list-group-item"><%= link_to msg.sender.first_name, "#{@user.id}/direct_message/#{msg.sender_id}" %> </li>
            <% end %>
    </ul>
    <% else %>
        <div class="card-body">
            <p class="card-text">No Messages! </p>
        </div>
    <% end %>
    </div>
</div>
</div>




    <!--    --> 
    <div class="d-flex justify-content-between">
        <div class="card" style="width: 20rem;">
            <div class="card-header text-white bg-dark">
                <h3>Popular Events</h3>
            </div>
                <% if @popular_events.length > 0 %> 
                <ul class="list-group list-group-flush">
                    <% @popular_events.each do |event|%>
                    <li class="list-group-item"><%=link_to event.title, event_path(event) %></li>
                    <% end %>
                </ul>
                <% else  %> 
                <div class="card-body">
                    <p class="card-text">There are no popular events!! </p>
                    <p class="card-text"><%=link_to "Search Events", events_path %></p>
                </div>
                <% end %> 
        </div>
    </div>
    <br>
    <br>

</div>