config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  get '/events/search', to: 'events#search'

  resources :group_messages, only: [:create]
  resources :direct_messages, only: [:create]
  #resources :event_users
  resources :events
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/users/:first_id/direct_message/:second_id', to: 'direct_messages#display_messages', as: 'display_direct_messages'
  get '/users/:user_id/group_message/:event_id', to: 'group_messages#display_messages', as: 'display_group_messages'

  get "/events/:event_id/register", to: "events#register", as: 'event_register_user'
  get "/events/:event_id/unregister", to: "events#unregister", as: 'event_unregister_user'
  #get "/events/:user_id/organizer", to: "events#organizer", as: 'organizer'
  post "/events/:event_id/organizer/add_member", to: "events#add_member", as: 'add_member'
  get "/events/:event_id/organizer/:member_id/remove_member", to: "events#remove_member", as: 'remove_member'


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' #make it post or delete

  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/event.rb
class Event < ApplicationRecord
    has_many :event_user, dependent: :destroy #singularized 
    has_many :users, through: :event_user
    has_many :group_messages

    validates :title, presence: true
    validates :description, presence: true
    validates :city, presence: { message: "is required for in-person event" }, unless: :virtual? 
    validates :state, presence: { message: "is required for in-person event" }, unless: :virtual?
    validates :start, presence: true
    validates :end, presence: true
    validate :end_time_later_than_start
    validate :start_time_must_be_in_future

    #This will generate the logitute and latitude of the address 
    geocoded_by :full_address
    after_validation :geocode
    # validates :start, numericality: {greater_than: DateTime.now}

    def full_address
       [street_address, city, state, zipcode].join(',')
    end 

    #returns true if user has already joined the event 
    def is_user_joined(user)
        if user 
            event_user = EventUser.find_by(event_id: self.id, user_id: user.id)
            event_user ? true : false 
        else 
            false 
        end

    end 

    #returns true if user is an organizer 
    def is_user_organizer(user)
        if user 
            event_user = EventUser.find_by(event_id: self.id, user_id: user.id)
            event_user ? event_user.organizer : false
        else 
            false 
        end 
    end 

    #return members of an event 
    def members 
        self.users 
    end 

    #return popular events (top 4 events with highest attendees)
    def self.popular 
        Event.order("users_count DESC").limit(4)    
    end 

    # custom validations
    def end_time_later_than_start
        if self.start >= self.end
            self.errors.add(:start, "date/time must be before End date/time")
        end
    end

    # need to fix timezones - DateTime.now uses EST zone
    #  but the db store in UTC 
    def start_time_must_be_in_future
        if self.start <= DateTime.now - 4.hours # to account for the timezone issue
            self.errors.add(:event,  "must be in the future")
        end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate, :except => [:index, :show, :search] #unregistered users can only see index of the events route

    def index
        @events = Event.where("public = ? AND end > ?", true, DateTime.now - 4.hours)
        @user = current_user
        @search_entry = nil
    end

    def show
        @event = Event.find(params[:id])
        @user = current_user 
        @joined = @event.is_user_joined(@user) #returns true if user has joined event
        @organizer = @event.is_user_organizer(@user) #returns true if user is an organzier

   #if event is private, restrict access to organizer and enrolled users only 
   
        if !@event.public && !@organizer && !@joined  
            redirect_back(fallback_location: events_path)
        end 
    end

    def new
        @event = Event.new()
    end

    def create
        @event = Event.create(event_params) #create an event 
        if @event.valid?
            EventUser.create(user_id: session[:user_id], event_id: @event.id, organizer: true) #creates assoication between creater(user) and event
            redirect_to event_path(@event)
        else 
            flash[:errors] = @event.errors.full_messages 
            redirect_to new_event_path

        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update 
        @event = Event.find(params[:id])
        @event.update(event_params)

        if @event.valid?
            redirect_to event_path(@event)
        else 
            flash[:errors] = @event.errors.full_messages 
            flash[:errors].unshift "Your event was not updated:"
            redirect_to edit_event_path
        end

    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to events_path
    end

    #Lets user join an event 
    def register 
        event = Event.find(params[:event_id])  #is it necessary to find the event? can't we just use the id from params
        EventUser.create(user_id: session[:user_id], event_id: event.id, organizer: false)
        redirect_to user_path(session[:user_id])
    end

    #Lets user leave an event 
    def unregister 
        event_user = EventUser.find_by(user_id: session[:user_id], event_id: params[:event_id])
        event_user.destroy
        redirect_to user_path(session[:user_id])
    end

    def search 
       if params[:events][:attr] == ""
            @events = Event.where(public: true)
            @user = current_user
       else 
            #@events = Event.where("title LIKE :title AND public  :public", { title: "%#{params[:events][:attr]}%", public: "%#{true}%"  })
            #@events = Event.where("title LIKE ? AND public LIKE ?", "%#{params[:events][:attr]}%", "true" )
            @events = Event.where("title LIKE ?", "%#{params[:events][:attr]}%") # How can we add an additional condition to return public events only 
            @user = current_user
            @search_entry = params[:events][:attr]
       end 
      
       render :index 
    end 


    def organizer
        @user = current_user
        @events = @user.organized_events 
    end 

    #Lets user join an event 
    def add_member 
        event = Event.find(params[:event_id])  #is it necessary to find the event? can't we just use the id from params
        user = User.find_by(email: params[:events][:email])
        if user  
            if !event.is_user_joined(user)
                EventUser.create(user_id: user.id, event_id: event.id, organizer: false)
                redirect_back(fallback_location: user_path(session[:user_id]))
            else 
                flash[:error] = "User already joined!"
                redirect_back(fallback_location: user_path(session[:user_id]))
            end 
        else 
            flash[:error] = "User doesn't exist "
            redirect_back(fallback_location: user_path(session[:user_id]))
        end 
    end

    def remove_member 

        event_user = EventUser.find_by(user_id: params[:member_id], event_id: params[:event_id])
        event_user.destroy
       
        redirect_back(fallback_location: event_path(params[:event_id]))
    
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :location_name, :street_address, :city, :state, :zipcode, :start, :end, :active, :public, :virtual)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">

    <% if flash[:errors] %>
        <div class="form-group row justify-content-center mt-2">
            <div class="col-lg-5">
                <% flash[:errors].each do |error| %>
                    <p style="color:red"> <%= error%> </p>
                <% end %>
            </div>
        </div>
    <% end %>
    <%= form_for @event do |f| %>
        <div class="form-group row justify-content-center">
            <div class="col-lg-5">

                <%= f.label :title  %>
                <%= f.text_field :title, class: "form-control"  %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <div class="col-lg-5">

                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control"  %>
            </div>
        </div>

        <div class="form-check text-center">

            <%= f.radio_button :virtual, false, :checked => true, class: "form-check-input" %>
            <%= f.label :virtual, "In-Person", class: "form-check-label" %>
       
            <%= f.radio_button :virtual, true, class: "form-check-input ml-2" %>
            <%= f.label :virtual, "Virtual", class: "form-check-label ml-4" %>
        </div>
        <br>

        <div class="form-group row justify-content-center">
            <div class="col-lg-5">

                <%= f.label :street_address  %>
                <%= f.text_field :street_address, class: "form-control"  %>
            </div>
        </div>


        <div class="form-group row justify-content-center">
            <div class="col-lg-5">

                <%= f.label :city  %>
                <%= f.text_field :city, class: "form-control"  %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <div class="col-lg-5">

                <%= f.label :state  %>
                <%= f.text_field :state, class: "form-control"  %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <div class="col-lg-5">

                <%= f.label :zipcode  %>
                <%= f.text_field :zipcode, class: "form-control"  %>
            </div>
        </div>


        <div class="form-group row justify-content-center">
            <div class="col-lg-5">
                <%= f.label :start  %>
                <%= f.datetime_select :start, class: "form-control"  %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
            <div class="col-lg-5">
                <%= f.label :end  %>
                <%= f.datetime_select :end, class: "form-control"  %>
            </div>        
        </div>

        <div class="form-check text-center">
            <%= f.radio_button :public, true, :checked => true, class: "form-check-input" %>
            <%= f.label :public, "Public", class: "form-check-label" %>

            <%= f.radio_button :public, false, class: "form-check-input ml-2" %>
            <%= f.label :public, "Private", class: "form-check-label ml-4" %>
        </div>
        <br>
        <div class="row justify-content-center">
            <%= f.submit class: "btn btn-primary mb-3"%>
        </div>
        <br>

    <% end  %>
    </div>

app/views/events/edit.html.erb
<h1 class="text-center mt-3">Update your Event: </h1>
<%= render "form" %>

app/views/events/index.html.erb
<div class="d-flex justify-content-center"> 
  <%= form_for( :events, as: :search, url: "/events/search", method: :get, html: { class: "d-inline-flex p-2 bd-highlight"})  do |f| %>
    <%= f.text_field :attr, placeholder: "Search", value:@search_entry, class: "form-control mr-sm-2"  %>
    <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>

  
  <% if current_user %>
    <div class = "mt-2">
      <%= button_to "Create Event", new_event_path, class: "btn btn-outline-dark ", :method => "get"%>
    </div>
  <% end %>
</div>
  <p style="color:red" class="text-center"><%= flash[:message] %></p>

<div class="m-4">
  <div class="row row-cols-1 row-cols-md-3">
    <% @events.each do |event| %>
      <div class="col mb-4">

        <div class="card  bg-light text-dark">
          <div class="card-body">
            <h3 class="card-title text-center"><%= link_to event.title, event_path(event), class: "text-dark" %></h3>
            <h6 class="card-text text-center"><%= !event.virtual ? "#{event.city}, #{event.state}" : "This event is virtual" %></h6>
            <p class="card-text text-center"><%= event.description %></p>
            <p class="card-text text-center"> <%= event.start.strftime("%A - %b %d, %Y  at %I:%M %p") %></p>

            <% if event.is_user_organizer(@user) %>
              <p class="text-info text-center">You organized this event</p>
            <% elsif event.is_user_joined(@user) %>
              <p class="text-success text-center">Already joined!</p>
            <% elsif current_user == nil %>
              <div class="text-center">
                <%= button_to "Join Event", "/login", :method => "get", class: "btn btn-dark"%>
              </div>
            <% else %>
              <div class="text-center">
                <%= button_to "Join Event", "/events/#{event.id}/register", :method => "get", class: "btn btn-dark"%>
              </div>
            <% end%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1 class="text-center mt-3">Create an Event: </h1>
<%= render "form" %>

app/views/events/organizer.html.erb
<!--
<h1>Organizer Page</h1>

<h3>You are the Organizer of the following events</h3>
<br>
<% @events.each do |event|%>
    <%= event.title %> 
    <ul class="list-group list-group-flush">
        <% event.members.each do |member| %>
            <li class="list-group-item"><a href="/users/<%=@user.id%>/direct_message/<%=member.id %>"><%= member.first_name%> <%=member.last_name %> </a></li>
        <% end %>
    </ul>
    
        <%= form_tag add_member_path  do %>
            <%= text_field_tag :email %>
            <%= hidden_field_tag "", params[:event_id] %>
            <%= submit_tag "Send", data: { disable_with: false }%>
        <% end %>
    
<%end%>

-->

app/views/events/show.html.erb
<div class="jumbotron container mt-5 pl-5 text-center">
    <h1 class="display-3"><%= @event.title %></h1>
     <% if @event.location_name%>
              <h5 class="card-text"><%= @event.location_name %></h6>
    <% end %>
    <% if @event.virtual %>
        <h4 class="lead text-info">This event is virtual</h4>
        <% else %>
        <h4 class="lead"><%= "#{@event.street_address}"%></h4>
        <h4 class="lead"><%= "#{@event.city}, #{@event.state} #{@event.zipcode}"%></h4>

    <% end %>
    <h4><%= @event.description %></h4>
    <h4 class="lead"><%= @event.start.strftime("%A - %b %d, %Y  at %I:%M %p") %></h4>
    <h4 class="lead"><%= @event.end.strftime("%A - %b %d, %Y  at %I:%M %p")  %></h4>

    <% if !@event.public %>
        <h4 class="lead" style="color:slategrey">This event is private</h4>
    <% end %>
    <br>
    <% if @user %>
        <% if !@joined %>
            <div class="text-center">  
                <%= button_to "Join Event", "/events/#{@event.id}/register", :method => "get", class: "btn btn-outline-info"%>
            </div>
        <% elsif @joined && @organizer %> 
        <div class="row justify-content-center">
            <div class="col-xs-4 ">
                <%= button_to "Event Chat", "/users/#{current_user.id}/group_message/#{@event.id}", :method => "get", class: "btn btn-outline-success"%>
            </div>
            <div class="col-xs-4 ml-5">
                <%= button_to "Delete Event", event_path(@event), :method => "delete", class: "btn btn-outline-danger"%>
            </div>
            <div class="col-xs-4 ml-5 ">
                <%= button_to "Update Event", edit_event_path(@event), :method => "get", class: "btn btn-outline-secondary" %>
            </div>
        </div>
        <% else %>

            <div class="row justify-content-center">
                <div class="col-xs-4 ">
                    <%= button_to "Event Chat", "/users/#{current_user.id}/group_message/#{@event.id}", :method => "get", class: "btn btn-outline-success"%>
                </div>
                <div class="col-xs-4 ml-5">
                    <%= button_to "Leave Event", "/events/#{@event.id}/unregister", :method => "get", class: "btn btn-outline-danger"%>
                </div>
            </div>

        <% end %>
    <% else %>
            <div class="text-center">  

        <p>You must be logged in to join this event</p>
        <%= button_to "Login", "/login", :method => "get", class: "btn btn-info"%>
        </div>
    <% end %>
    <br>
    <br>
    <br>
    <div id="map"></div>
</div>




    <title>Simple Map</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=**************************************&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
    <style type="text/css">
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 50vh;
      }
    </style>
    <script>
      (function(exports) {
        "use strict";

        function initMap() {
            var myLatLng = {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};
          exports.map = new google.maps.Map(document.getElementById("map"), {
            center: myLatLng,
            zoom: 14
          });
          var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Your Event Location'
        });
        }

        exports.initMap = initMap;
      })((this.window = this.window || {}));
    </script>